version: '3.8'

services:
  ycloud-mcp:
    build: .
    ports:
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./temp:/app/temp
      - ~/.ssh/ycloud:/app/ycloud_key:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        node mcp-ycloud-server.js &
        node mcp-http-server.js &
        node file-upload-server.js &
        wait
      "
